EXEC IncluiNotasDia '2022-01-01'
EXEC IncluiNotasDia '2022-01-02'
EXEC IncluiNotasDia '2022-01-03'
EXEC cargaBase 2022, 1, 2022, 2

SELECT COUNT(*) AS NUMERO_NOTAS FROM tb_nota ;

DBCC SHRINKDATABASE ('dbVendas',TRUNCATEONLY);


SELECT COUNT(*) AS NUMERO_NOTAS FROM tb_nota ;

BACKUP DATABASE dbVendas TO DISK = 'D:\SQL BASE\DATA\BACKUP\DBVENDAS.BAK';

EXEC IncluiNotasDia '2022-03-01'

BACKUP DATABASE dbVendas TO DISK = 'D:\SQL BASE\DATA\BACKUP\DBVENDAS2.BAK';

EXEC IncluiNotasDia '2022-03-02'

SELECT COUNT(*) AS NUMERO_NOTAS FROM tb_nota ;

BACKUP DATABASE dbVendas TO DISK = 'D:\SQL BASE\DATA\BACKUP\DBVENDAS3.BAK';
