SELECT * FROM TABELA_DE_CLIENTES;

SELECT NOME, LOWER(NOME) AS NOME_MINUSCULO, UPPER(NOME) AS NOME_MAIUSCULO 
FROM TABELA_DE_CLIENTES;


SELECT NOME, CONCAT(ENDERECO_1, ' ', BAIRRO, ' ', CIDADE, ' ', ESTADO, '-', CEP) AS ENDERECO_COMPLETO
FROM TABELA_DE_CLIENTES;

SELECT NOME, SUBSTRING(NOME, 1, CHARINDEX(' ', NOME, 1))
FROM TABELA_DE_CLIENTES;



SELECT CHARINDEX(' ', NOME, 1)
FROM TABELA_DE_CLIENTES;

SELECT NOME
FROM TABELA_DE_CLIENTES;