
SELECT * FROM SUCOS_VENDAS.dbo.[TABELA DE CLIENTES];

SELECT COUNT(*) FROM [TABELA DE CLIENTES];

SELECT X.CPF, X.NOME 
FROM  (
	SELECT Row_Number() Over (Order By CPF) as RowNum, *
	FROM [TABELA DE CLIENTES]
) X
WHERE X.RowNum = 3;

--#########################
DECLARE @CPF VARCHAR(20);
DECLARE @NOME VARCHAR(100);
DECLARE @NUMERO_CLIENTES INT;
DECLARE @I INT;
SELECT @NUMERO_CLIENTES = COUNT(*) FROM [TABELA DE CLIENTES];

SET @I = 1;
WHILE @I <= @NUMERO_CLIENTES
	BEGIN
		SELECT @CPF = X.CPF, @NOME = X.NOME 
		FROM  (
			SELECT Row_Number() Over (Order By CPF) as RowNum, *
			FROM [TABELA DE CLIENTES]
		) X
		WHERE X.RowNum = @I;
		PRINT @CPF + ' - ' + @NOME;
		SET @I = @I + 1;
	END;

SELECT * FROM [TABELA DE PRODUTOS];
SELECT COUNT(*) FROM [TABELA DE PRODUTOS];

--#############################################
DECLARE @PRODUTO VARCHAR(50)
DECLARE @CODIGO VARCHAR(50)
DECLARE @I INT;
DECLARE @NUMERO_PRODUTOS INT;
SELECT @NUMERO_PRODUTOS = COUNT(*) FROM [TABELA DE PRODUTOS];

SET @I = 1;
WHILE @I <= @NUMERO_PRODUTOS
	BEGIN
		SELECT @PRODUTO = X.[NOME DO PRODUTO] , @CODIGO = X.[CODIGO DO PRODUTO]
		FROM(
			SELECT Row_Number() Over (Order By [CODIGO DO PRODUTO]) as RowNum, *
			FROM [TABELA DE PRODUTOS]
		) AS X
		WHERE X.RowNum = @I;
		PRINT @PRODUTO + ' - ' + @CODIGO;
		SET	@I = @I + 1;
	END;

SELECT * FROM [NOTAS FISCAIS]
WHERE YEAR([DATA]) = 2015;

SELECT * FROM [NOTAS FISCAIS]
WHERE DATA BETWEEN '2015-01-01' AND '2015-12-31';

--###############################
DECLARE @CPF VARCHAR(11);
DECLARE @NOME VARCHAR(100);
DECLARE @NUMERO_CLIENTES INT;
DECLARE @I INT;
DECLARE @MES INT, @ANO INT;
DECLARE @TOTAL_VENDAS FLOAT;
DECLARE @TABELA_FINAL TABLE (CPF VARCHAR(11), NOME VARCHAR(100), MES INT, ANO INT, VALOR_TOTAL FLOAT);

SET @MES = 2;
SET @ANO = 2015;
SELECT @NUMERO_CLIENTES = COUNT(*) FROM [TABELA DE CLIENTES];
SET @I = 1;
WHILE @I <= @NUMERO_CLIENTES
BEGIN
        SELECT @CPF = X.CPF, @NOME = X.NOME
        FROM ( SELECT Row_Number() Over (Order By CPF) as RowNum, * FROM [TABELA DE CLIENTES]) X
        WHERE X.RowNum = @I;

        SELECT 
        @TOTAL_VENDAS = SUM([ITENS NOTAS FISCAIS].QUANTIDADE * [ITENS NOTAS FISCAIS].[PREÇO])
        FROM [NOTAS FISCAIS] 
        INNER JOIN [ITENS NOTAS FISCAIS]
        ON [NOTAS FISCAIS].NUMERO = [ITENS NOTAS FISCAIS].NUMERO
        WHERE [NOTAS FISCAIS].CPF = @CPF
        AND YEAR([NOTAS FISCAIS].DATA) = @ANO AND MONTH([NOTAS FISCAIS].DATA) = @MES;

        INSERT INTO @TABELA_FINAL VALUES (@CPF, @NOME, @MES, @ANO, @TOTAL_VENDAS);

        PRINT 'Vendas para ' + @CPF + ' - ' + @NOME + ' NO MÊS ' + CONVERT(VARCHAR(2), @MES) + ' E ANO ' + CONVERT(VARCHAR(4),@ANO) + ' FOI DE ' + TRIM(STR(@TOTAL_VENDAS, 15, 2));
        SET @I = @I + 1;

END;

SELECT * FROM @TABELA_FINAL

--#######################################

/*SELECT SUM([ITENS NOTAS FISCAIS].QUANTIDADE * [ITENS NOTAS FISCAIS].[PREÇO]) 
FROM [NOTAS FISCAIS]
INNER JOIN [ITENS NOTAS FISCAIS] 
ON [NOTAS FISCAIS].NUMERO = [ITENS NOTAS FISCAIS].NUMERO
WHERE  [ITENS NOTAS FISCAIS].[CODIGO DO PRODUTO] = @CODIGO
AND YEAR([NOTAS FISCAIS].DATA) = @ANO AND MONTH([NOTAS FISCAIS].DATA) = @MES;
*/

DECLARE @CODIGO VARCHAR(50);
DECLARE @NOME_PRODUTO VARCHAR(50);
DECLARE @QUANTIDADE_VENDAS_TOTAL INT;
DECLARE @I INT;
DECLARE @NUMERO_PRODUTOS INT;

SELECT @NUMERO_PRODUTOS = COUNT(*) FROM [TABELA DE PRODUTOS];
SET @I = 1;

WHILE @I <= @NUMERO_PRODUTOS
	BEGIN
		SELECT @CODIGO = X.[CODIGO DO PRODUTO]
		FROM (
			SELECT Row_Number() Over (Order By [CODIGO DO PRODUTO]) as RowNum, *
			FROM [TABELA DE PRODUTOS]      
		) X
		 WHERE X.RowNum = @I;

		 SELECT 
                @QUANTIDADE_VENDAS_TOTAL = SUM([ITENS NOTAS FISCAIS].QUANTIDADE)
                FROM [NOTAS FISCAIS]
				INNER JOIN [ITENS NOTAS FISCAIS] 
				ON [NOTAS FISCAIS].NUMERO = [ITENS NOTAS FISCAIS].NUMERO
				WHERE  [ITENS NOTAS FISCAIS].[CODIGO DO PRODUTO] = @CODIGO
		 	 
   PRINT 'Vendas para ' + @CODIGO + ' - ' + CONVERT(VARCHAR(20), @QUANTIDADE_VENDAS_TOTAL);
   SET @I = @I + 1;
	END;


	SELECT [NOME DO PRODUTO], SUM(QUANTIDADE)
	FROM [TABELA DE PRODUTOS]
	INNER JOIN [ITENS NOTAS FISCAIS]
    ON [TABELA DE PRODUTOS].[CODIGO DO PRODUTO] = [ITENS NOTAS FISCAIS].[CODIGO DO PRODUTO]
	WHERE [ITENS NOTAS FISCAIS].[CODIGO DO PRODUTO] = 1002334
	GROUP BY [NOME DO PRODUTO];

--##############################################


