SELECT GETDATE()

SELECT DATEADD(DAY, 10, GETDATE());

SELECT NOME, CONCAT(DATENAME(weekday, DATA_DE_NASCIMENTO), DATENAME(MONTH, DATA_DE_NASCIMENTO), DATENAME(YEAR, DATA_DE_NASCIMENTO))
FROM TABELA_DE_CLIENTES;

SELECT *
FROM NOTAS_FISCAIS
WHERE NUMERO = 100;

SELECT NUMERO, QUANTIDADE, PRECO
FROM ITENS_NOTAS_FISCAIS
WHERE NUMERO = 100;

SELECT NUMERO, QUANTIDADE,ROUND(QUANTIDADE * PRECO, 1) AS FATURAMENTO, 
SUM(FATURAMENTO)
FROM ITENS_NOTAS_FISCAIS
WHERE NUMERO = 100;

SELECT YEAR(DATA_VENDA) AS ANO, FLOOR(SUM(IMPOSTO * (INF.QUANTIDADE * INF.PRECO))) AS IMPOSTO_TOTAL
FROM NOTAS_FISCAIS NF
INNER JOIN ITENS_NOTAS_FISCAIS INF ON NF.NUMERO = INF.NUMERO
WHERE YEAR(DATA_VENDA) = 2016
GROUP BY YEAR(DATA_VENDA);

SELECT YEAR(DATA_VENDA) AS ANO, FLOOR(SUM(IMPOSTO * (QUANTIDADE * PRECO))) 
FROM NOTAS_FISCAIS NF
INNER JOIN ITENS_NOTAS_FISCAIS INF ON NF.NUMERO = INF.NUMERO
WHERE YEAR(DATA_VENDA) = 2016
GROUP BY YEAR(DATA_VENDA);

--, SUM(IMPOSTO * SUM(INF.QUANTIDADE * INF.PRECO))

SELECT DATA_DE_NASCIMENTO, CONVERT(VARCHAR(25), DATA_DE_NASCIMENTO, 121) 
FROM TABELA_DE_CLIENTES;

SELECT DATA_DE_NASCIMENTO, CONVERT(VARCHAR(25), DATA_DE_NASCIMENTO, 106) 
FROM TABELA_DE_CLIENTES;

SELECT NOME_DO_PRODUTO, PRECO_DE_LISTA FROM TABELA_DE_PRODUTOS;
SELECT NOME_DO_PRODUTO, CONCAT('O preço de lista é: ', PRECO_DE_LISTA) AS PRECO 
FROM TABELA_DE_PRODUTOS;

SELECT NOME_DO_PRODUTO, 
CONCAT('O preço de lista é: ', CAST(PRECO_DE_LISTA AS VARCHAR(10))) AS PRECO 
FROM TABELA_DE_PRODUTOS;


SELECT  *
FROM TABELA_DE_CLIENTES;

SELECT TOP 10 * FROM ITENS_NOTAS_FISCAIS;

SELECT TOP 10 * FROM NOTAS_FISCAIS
WHERE CPF = '7771579779';

SELECT * FROM TABELA_DE_CLIENTES
WHERE CPF = '7771579779';

SELECT YEAR(NF.DATA_VENDA) AS ANO, TC.NOME, 
CONCAT('O cliente: ', TC.NOME, 'comprou: R$', TRIM(STR(SUM(INF.QUANTIDADE * INF.PRECO) ,10,2)), 
' no ano de 2016') AS TOTAL_COMPRADO, SUM(INF.QUANTIDADE * INF.PRECO)
FROM TABELA_DE_CLIENTES TC
INNER JOIN NOTAS_FISCAIS NF ON TC.CPF = NF.CPF
INNER JOIN ITENS_NOTAS_FISCAIS INF ON NF.NUMERO = INF.NUMERO
GROUP BY YEAR(DATA_VENDA), TC.NOME
HAVING YEAR(DATA_VENDA) = 2016;


--SELECT STR(123.45, 6, 1);
--CONCAT('O cliente: ', TC.NOME, 'comprou: R$', 
--	SUM(INF.QUANTIDADE * INF.PRECO), 'no ano de 2016')





--FROM NOTAS_FISCAIS NF
--INNER JOIN ITENS_NOTAS_FISCAIS INF ON NF.NUMERO = INF.NUMERO