SELECT TOP (1000) [NUMERO]
      ,[CODIGO]
      ,[QUANTIDADE]
      ,[PRECO]
  FROM [VENDAS SUCOS].[dbo].[TABELA_DE_ITENS_VENDIDOS]

  SELECT TOP 10 * FROM TABELA_DE_VENDAS;

  UPDATE PRODUTOS SET PRECO_LISTA = 5 WHERE CODIGO = '1040107';

  SELECT * FROM PRODUTOS WHERE CODIGO = '1040107';

  UPDATE CLIENTES SET ENDERECO = 'R. Jorge Emilio 23', BAIRRO = 'Santo Amaro',
	CIDADE = 'São Paulo', ESTADO = 'SP', CEP = '8833223'
	WHERE CPF = '19290992743';

	SELECT * FROM CLIENTES WHERE CPF = '19290992743';


	UPDATE PRODUTOS SET 
    DESCRITOR = replace(DESCRITOR, '350 ml', '550 ml'), 
    TAMANHO = '550 ml' 
WHERE TAMANHO = '350 ml';

SELECT * FROM CLIENTES WHERE ESTADO = 'RJ';

SELECT *, VOLUME_COMPRA = REPLACE(VOLUME_COMPRA, VOLUME_COMPRA, VOLUME_COMPRA*1.20)
FROM CLIENTES;

UPDATE CLIENTES 
SET VOLUME_COMPRA = VOLUME_COMPRA*1.20
WHERE ESTADO = 'RJ';

UPDATE SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS SET 
PRECO_DE_LISTA = PRECO_DE_LISTA * 1.20;

SELECT 
A.CODIGO AS CODIGO_MINHA_TABELA, A.PRECO_LISTA AS PRECO_MINHA_TABELA, 
B.CODIGO_DO_PRODUTO AS CODIGO_TABELA_APOIO, B.PRECO_DE_LISTA AS PRECO_TABELA_APOIO 
FROM PRODUTOS A 
INNER JOIN SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS B 
ON A.CODIGO = B.CODIGO_DO_PRODUTO;

UPDATE A SET A.PRECO_LISTA = B.PRECO_DE_LISTA 
FROM PRODUTOS A 
INNER JOIN SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS B 
ON A.CODIGO = B.CODIGO_DO_PRODUTO;

