
CREATE FUNCTION FaturamentoNota (@NUMERO AS INT)
RETURNS FLOAT
AS
BEGIN
	DECLARE @FATURAMENTO FLOAT
	SELECT @FATURAMENTO = SUM(QUANTIDADE * [PREÇO])
	FROM [ITENS NOTAS FISCAIS]
	WHERE NUMERO = @NUMERO
	RETURN @FATURAMENTO
END;

SELECT NUMERO, dbo.FaturamentoNota(NUMERO) AS FATURAMENTO
FROM [NOTAS FISCAIS];

--##########################################################

SELECT ROUND(((500 - 100 - 1) * RAND() + 100), 0);

CREATE VIEW VW_ALEATORIO1 AS SELECT RAND() AS VALOR_ALEATORIO
SELECT * FROM VW_ALEATORIO1;

CREATE FUNCTION NumeroAleatorio(@VAL_MIN INT, @VAL_MAX INT)
RETURNS INT
AS
BEGIN
  DECLARE @ALEATORIO INT
  DECLARE @VALOR_ALEATORIO FLOAT
  SELECT @VALOR_ALEATORIO = VALOR_ALEATORIO FROM VW_ALEATORIO1
  SET @ALEATORIO = ROUND((@VAL_MAX - @VAL_MIN - 1) * @VALOR_ALEATORIO + @VAL_MIN, 0)
  RETURN @ALEATORIO
END;

SELECT dbo.[NumeroAleatorio](1,10)


--##########################################################

CREATE FUNCTION FaturamentoBairro (@BAIRRO VARCHAR(50))
RETURNS FLOAT
AS
BEGIN
   DECLARE @FATURAMENTO FLOAT
   SELECT @FATURAMENTO = SUM(INF.QUANTIDADE * INF.[PREÇO]) 
   FROM [ITENS NOTAS FISCAIS] INF
   INNER JOIN [NOTAS FISCAIS] NF
   ON INF.NUMERO = NF.NUMERO
   INNER JOIN [TABELA DE CLIENTES] TC
   ON TC.CPF = NF.CPF
   WHERE TC.BAIRRO = @BAIRRO
   RETURN @FATURAMENTO
END;

SELECT dbo.FaturamentoBairro('Jardins') 
FROM [NOTAS FISCAIS];

