SELECT A.CPF FROM [dbo].[CLIENTES] A
INNER JOIN [dbo].[VENDEDORES] B
ON A.[BAIRRO] = B.[BAIRRO];



UPDATE C SET C.VOLUME_COMPRA = C.VOLUME_COMPRA * 1.30
FROM CLIENTES C
INNER JOIN VENDEDORES V
ON V.BAIRRO = C.BAIRRO;


SELECT C.VOLUME_COMPRA
FROM CLIENTES C
INNER JOIN VENDEDORES V
ON V.BAIRRO = C.BAIRRO;



MERGE INTO PRODUTOS A
USING SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS B
ON A.CODIGO = B.CODIGO_DO_PRODUTO
WHEN MATCHED THEN
UPDATE SET A.PRECO_LISTA = B.PRECO_DE_LISTA;


SELECT C.VOLUME_COMPRA, TB.VOLUME_DE_COMPRA
FROM CLIENTES C
INNER JOIN SUCOS_FRUTAS.DBO.TABELA_DE_CLIENTES TB
ON C.BAIRRO  = TB.BAIRRO;

SELECT C.NOME, VOLUME_COMPRA, TC.NOME, TC.VOLUME_DE_COMPRA
FROM CLIENTES C
INNER JOIN SUCOS_FRUTAS.DBO.TABELA_DE_CLIENTES TC
ON C.CPF = TC.CPF

MERGE INTO CLIENTES C
USING SUCOS_FRUTAS.DBO.TABELA_DE_CLIENTES TC
ON C.CPF = TC.CPF
WHEN MATCHED THEN
UPDATE SET C.VOLUME_COMPRA = TC.VOLUME_DE_COMPRA;

MERGE INTO PRODUTOS A
USING SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS B
ON A.CODIGO = B.CODIGO_DO_PRODUTO
WHEN MATCHED THEN
UPDATE SET A.PRECO_LISTA = B.PRECO_DE_LISTA;

SELECT * from [PRODUTOS] WHERE SUBSTRING([DESCRITOR],1,15) = 'Sabor dos Alpes'


SELECT * FROM PRODUTOS
WHERE CODIGO NOT IN (SELECT CODIGO_DO_PRODUTO FROM SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS);

DELETE FROM PRODUTOS
WHERE CODIGO NOT IN (SELECT CODIGO_DO_PRODUTO FROM SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS);

SELECT A.NUMERO FROM TABELA_DE_VENDAS A
INNER JOIN CLIENTES B ON A.CPF = B.CPF
WHERE B.IDADE < 18;

SELECT * FROM TABELA_DE_VENDAS TB
INNER JOIN CLIENTES C
ON TB.CPF = C.CPF
WHERE C.IDADE > 18;

SELECT * FROM CLIENTES WHERE IDADE < 18;