


SELECT * FROM [TABELA DE CLIENTES];

SELECT COUNT(*) FROM [TABELA DE CLIENTES];

SELECT DBO.NumeroAleatorio(1,16);

DECLARE @CLIENTE_ALEATORIO VARCHAR(12);
DECLARE @VALOR_INICIAL INT;
DECLARE @VALOR_FINAL INT;
DECLARE @ALEATORIO INT;
DECLARE @CONTADOR INT = 1;
SET @VALOR_INICIAL = 1;
SELECT @VALOR_FINAL = COUNT(*) FROM [TABELA DE CLIENTES];
SET @ALEATORIO = DBO.NumeroAleatorio(@VALOR_INICIAL, @VALOR_FINAL);
DECLARE CURSOR1 CURSOR FOR SELECT CPF FROM [TABELA DE CLIENTES];

OPEN CURSOR1

FETCH NEXT FROM CURSOR1 INTO @CLIENTE_ALEATORIO
WHILE @CONTADOR < @ALEATORIO
BEGIN
	FETCH NEXT FROM CURSOR1 INTO @CLIENTE_ALEATORIO
	SET @CONTADOR = @CONTADOR + 1
END;
CLOSE CURSOR1
DEALLOCATE CURSOR1


SELECT @CLIENTE_ALEATORIO
UNION 
SELECT NOME FROM [TABELA DE CLIENTES]
WHERE CPF = @CLIENTE_ALEATORIO

--############################

SELECT COUNT(*) FROM [TABELA DE VENDEDORES];

DECLARE @ALEATORIO INT;
DECLARE @CONTADOR INT = 1;
DECLARE @MINIMO_VENDEDORES INT = 1;
DECLARE @TOTAL_VENDEDORES INT;
DECLARE @VENDEDOR_ALEATORIO INT;
SELECT @TOTAL_VENDEDORES = COUNT(*) FROM [TABELA DE VENDEDORES];
SELECT @ALEATORIO = DBO.NumeroAleatorio(@MINIMO_VENDEDORES, @TOTAL_VENDEDORES);
DECLARE CURSOR_VENDEDOR CURSOR FOR SELECT MATRICULA FROM [TABELA DE VENDEDORES]
OPEN CURSOR_VENDEDOR

FETCH NEXT FROM CURSOR_VENDEDOR INTO @VENDEDOR_ALEATORIO

WHILE @CONTADOR < @VENDEDOR_ALEATORIO
BEGIN
	FETCH NEXT FROM CURSOR_VENDEDOR INTO @VENDEDOR_ALEATORIO
	SET @CONTADOR = @CONTADOR +1
END;
PRINT @VENDEDOR_ALEATORIO;

CLOSE CURSOR_VENDEDOR;
DEALLOCATE CURSOR_VENDEDOR;


SELECT * FROM [TABELA DE VENDEDORES];