--DECLARE @MATRICULA VARCHAR(5);
--DECLARE @NOME VARCHAR(100);
--DECLARE @PERCENTUAL FLOAT;
--DECLARE @DATA DATE;
--DECLARE @FERIAS BIT;
--DECLARE @BAIRRO VARCHAR(50);

DECLARE @MATRICULA VARCHAR(5), @NOME VARCHAR(100), @PERCENTUAL FLOAT;
DECLARE @DATA DATE, @FERIAS BIT, @BAIRRO VARCHAR(50);

SET @MATRICULA = '00240';
SET @NOME = 'Cláudia Rodrigues';
SET @PERCENTUAL = 0.10;
SET @DATA = '2012-03-12';
SET @FERIAS = 1;
SET @BAIRRO = 'Jardins';

PRINT @MATRICULA;
PRINT @NOME;
PRINT @PERCENTUAL;
PRINT @DATA;
PRINT @FERIAS;
PRINT @BAIRRO;

DECLARE @MATRICULA VARCHAR(5), @NOME VARCHAR(100), @PERCENTUAL FLOAT;

SET @MATRICULA = '00240';
SET @NOME = 'Cláudia Rodrigues';
SET @PERCENTUAL = 0.10;

INSERT INTO [TABELA DE VENDEDORES]
(MATRICULA, NOME, [PERCENTUAL COMISSAO])
VALUES
(@MATRICULA, @NOME, @PERCENTUAL);
SELECT * FROM [TABELA DE VENDEDORES];


--##################################
DECLARE @Cliente VARCHAR(10)
DECLARE @Idade INT
DECLARE @DataNascimento DATE
DECLARE @Custo FLOAT
SET @Cliente = 'João'
SET @Idade = 10
SET @DataNascimento = '20170110'
SET @Custo = 10.23



--DECLARE @Cliente VARCHAR(10);
--DECLARE @Idade INT;
--DECLARE @DataNascimento DATE;
--DECLARE @Custo FLOAT;
--##############################

DECLARE @CPF VARCHAR(50);
DECLARE @NOME VARCHAR(100);
DECLARE @DATA_NASCIMENTO DATE; 
DECLARE @IDADE INT;

SET @CPF = '19290992743';

SELECT @NOME = NOME, @DATA_NASCIMENTO = [DATA DE NASCIMENTO], @IDADE = IDADE FROM [TABELA DE CLIENTES] WHERE CPF = @CPF;

PRINT @NOME;
PRINT @DATA_NASCIMENTO;
PRINT @IDADE;

SELECT * FROM [TABELA DE CLIENTES];


SELECT @NOME = NOME, @DATA_NASCIMENTO = [DATA DE NASCIMENTO], @IDADE = IDADE
FROM [TABELA DE CLIENTES] 
WHERE CPF = @CPF;

DECLARE @NUMNOTAS INT;
SELECT @NUMNOTAS = COUNT(*) FROM [NOTAS FISCAIS]
WHERE DATA = '01-01-2017';
PRINT @NUMNOTAS;


