CREATE TABLE TAB_IDENTITY
(ID INT IDENTITY(1,1) NOT NULL,
DESCRITOR VARCHAR(20) NULL);

SELECT * FROM TAB_IDENTITY;

INSERT INTO TAB_IDENTITY (DESCRITOR) VALUES ('CLIENTE X');
INSERT INTO TAB_IDENTITY (DESCRITOR) VALUES ('CLIENTE Y');
INSERT INTO TAB_IDENTITY (DESCRITOR) VALUES ('CLIENTE Z');
INSERT INTO TAB_IDENTITY (DESCRITOR) VALUES ('CLIENTE W');
INSERT INTO TAB_IDENTITY (DESCRITOR) VALUES ('CLIENTE A');

SELECT * FROM TAB_IDENTITY;


DELETE FROM TAB_IDENTITY WHERE ID = 1;



CREATE TABLE TAB_IDENTITY2
(ID INT IDENTITY(100,4) NOT NULL,
DESCRITOR VARCHAR(20) NULL);

SELECT * FROM TAB_IDENTITY2;

INSERT INTO TAB_IDENTITY2 (DESCRITOR) VALUES ('CLIENTE X');
INSERT INTO TAB_IDENTITY2 (DESCRITOR) VALUES ('CLIENTE Y');
INSERT INTO TAB_IDENTITY2 (DESCRITOR) VALUES ('CLIENTE Z');
INSERT INTO TAB_IDENTITY2 (DESCRITOR) VALUES ('CLIENTE W');

CREATE TABLE TAB_FATURAMENTO (
    DATA_VENDA DATE NULL, 
    TOTAL_VENDA FLOAT
);

CREATE TRIGGER TG_ITENS_VENDIDOS 
ON [dbo].[TABELA_DE_ITENS_VENDIDOS] 
AFTER INSERT, UPDATE, DELETE 
AS 
BEGIN 
DELETE FROM TAB_FATURAMENTO;

INSERT INTO TAB_FATURAMENTO 
SELECT 
    TV.DATA_VENDA, 
    SUM (TIV.QUANTIDADE * TIV.PRECO) AS TOTAL_VENDA 
FROM TABELA_DE_VENDAS TV 
INNER JOIN TABELA_DE_ITENS_VENDIDOS TIV 
ON TV.NUMERO = TIV.NUMERO 
GROUP BY TV.DATA_VENDA;

END;


INSERT INTO TABELA_DE_VENDAS 
VALUES ('0105', '2018-05-16', '1471156710', '235', 0.18);

INSERT INTO TABELA_DE_ITENS_VENDIDOS 
VALUES ('0105', '1000889', 150, 10);


SELECT CPF, IDADE, DATA_NASCIMENTO, 
    DATEDIFF(YEAR, DATA_NASCIMENTO, GETDATE()) 
FROM CLIENTES


CREATE TRIGGER TG_CLIENTES_IDADE 
ON CLIENTES
AFTER INSERT, UPDATE, DELETE
AS
BEGIN 
UPDATE CLIENTES SET IDADE = 
    DATEDIFF(YEAR, DATA_NASCIMENTO, GETDATE());
END;


INSERT INTO [dbo].[CLIENTES]

UPDATE CLIENTES SET DATA_NASCIMENTO = '2018-05-16' WHERE CPF = '1471156710';

SELECT * FROM CLIENTES;



SELECT CPF, IDADE, DATA_NASCIMENTO, 
    DATEDIFF(YEAR, DATA_NASCIMENTO, GETDATE()) 
FROM CLIENTES
WHERE CPF = '1471156710';

SELECT CPF, IDADE, DATA_NASCIMENTO
FROM CLIENTES
WHERE CPF = '1471156710';

CREATE TABLE TAB_CHECK (
    ID INT NOT NULL, 
    NOME VARCHAR(50) NULL, 
    IDADE INT NULL, 
    CIDADE VARCHAR(50) NULL, 
    CONSTRAINT CHK_IDADE2 CHECK (
        (IDADE >= 18 AND CIDADE = 'RIO DE JANEIRO') 
        OR 
        (IDADE >= 16 AND CIDADE = 'SÃO PAULO')
    )
);