

RESTORE HEADERONLY FROM DISK = 'F:\DATA\BACKUP\DBVENDAS_3.BAK';

USE MASTER
DROP DATABASE dbVendas
RESTORE DATABASE dbVendas FROM DISK = 'D:\SQL BASE\DATA\BACKUP\DBVENDAS3.BAK' WITH RECOVERY;

SELECT COUNT(*) FROM [dbo].[tb_nota];


--######################################################

CREATE TABLE tb_controle_backups 
(ID INTEGER, NOME VARCHAR(100), NUMERO_NOTAS INT);

-- 1 DA MANHA - FULL (DATABASE WITH INT)

EXEC IncluiNotasDia '2022-03-02'
DECLARE @NUM_NOTAS INTEGER;
SELECT @NUM_NOTAS = COUNT(*) FROM tb_nota; 
INSERT INTO tb_controle_backups VALUES (1, 'BACKUP FULL 1 AM', @NUM_NOTAS);
SELECT * FROM tb_controle_backups

BACKUP DATABASE dbVendas TO DISK = 'D:\SQL BASE\DATA\BACKUP\POLITICA_BACKUP_20220302.BAK' WITH INIT;


-- 4 DA MANHÃ - INCREMENTAL (LOG WITH NOINT)

EXEC IncluiNotasDia '2022-03-02'
DECLARE @NUM_NOTAS INTEGER;
SELECT @NUM_NOTAS = COUNT(*) FROM tb_nota;
INSERT INTO tb_controle_backups VALUES (2, 'BACKUP INCREMENTAL 4 AM', @NUM_NOTAS);
SELECT * FROM tb_controle_backups

BACKUP LOG dbVendas TO DISK = 'D:\DATA\BACKUP\POLITICA_BACKUP_20220302.BAK' WITH NOINIT;

--####################################


-- 9 DA MANHÃ - FULL (DATABASE WITH DIFFERENTIAL)

EXEC IncluiNotasDia '2022-03-02'
DECLARE @NUM_NOTAS INTEGER;
SELECT @NUM_NOTAS COUNT(*) FROM tb_nota;
INSERT INTO tb_controle_backups VALUES (5, 'BACKUP DIFFERENTIAL 9 AM', @NUM_NOTAS);
SELECT * FROM tb_controle_backups 

BACKUP DATABASE dbVendas TO DISK = 'D:\DATA\BACKUP \POLITICA_BACKUP_20220302.BAK' WITH DIFFERENTIAL;






