CREATE DATABASE [VENDAS SUCOS];

CREATE DATABASE [VENDAS SUCOS 2]
ON(
NAME='VENDAS_SUCOS_2_DAT',
FILENAME='c:\TEMP\VENDAS_SUCOS_02.MDF',
SIZE=10MB,
MAXSIZE=50MB,
FILEGROWTH=5MB
) 
LOG ON(
NAME='VENDAS_SUCOS_2_LOG',
FILENAME='C:\TEMP\VENDAS_SUCOS_02.LDF',
SIZE=10MB,
MAXSIZE=50MB,
FILEGROWTH=5MB
);

CREATE TABLE PRODUTOS (
CODIGO VARCHAR(10) NOT NULL,
DESCRITOR VARCHAR(100) NULL,
SABOR VARCHAR(50) NULL,
TAMANHO VARCHAR(50) NULL,
EMBALAGEM VARCHAR(50) NULL,
PRECO_LISTA FLOAT NULL,
PRIMARY KEY (CODIGO)
);

CREATE TABLE VENDEDORES(
MATRICULA VARCHAR(5) NOT NULL,
NOME VARCHAR(100) NULL,
BAIRRO VARCHAR(50) NULL,
COMISSAO FLOAT NULL,
DATA_ADMISSAO DATE NULL,
FERIAS BIT NULL,
PRIMARY KEY (MATRICULA)
);

CREATE TABLE CLIENTES
(
CPF VARCHAR(11) NOT NULL,
NOME VARCHAR(100) NULL,
ENDERECO VARCHAR(100) NULL,
BAIRRO VARCHAR(50) NULL,
CIDADE VARCHAR(50) NULL,
ESTADO VARCHAR(50) NULL,
CEP VARCHAR(8) NULL,
DATA_NASCIMENTO DATE NULL,
IDADE INTEGER NULL,
GENERO VARCHAR(1) NULL,
LIMITE_CREDITO FLOAT,
VOLUME_COMPRA FLOAT,
PRIMEIRA_COMPRA BIT,
PRIMARY KEY (CPF)
);

CREATE TABLE TABELA_DE_VENDAS (
    NUMERO VARCHAR(5) NOT NULL, 
    DATA_VENDA DATE NULL, 
    CPF VARCHAR(11) NOT NULL, 
    MATRICULA VARCHAR(11) NOT NULL, 
    IMPOSTO FLOAT NULL, 
    PRIMARY KEY (NUMERO)
);

ALTER TABLE TABELA_DE_VENDAS
ADD CONSTRAINT FK_CLIENTES
FOREIGN KEY(CPF) REFERENCES CLIENTES(CPF);


ALTER TABLE TABELA_DE_VENDAS
ADD CONSTRAINT FK_VENDEDORES
FOREIGN KEY (MATRICULA) REFERENCES VENDEDORES(MATRICULA);

ALTER TABLE TABELA_DE_VENDAS
ALTER COLUMN MATRICULA VARCHAR(5) NOT NULL;

/* Numero (PK) e (FK - Tabela de Vendas) - Varchar(5)
Codigo (PK) e (FK - Tabela de Produtos) - Varchar(10)
Quantidade - Int32
Preco - Float */

CREATE TABLE TABELA_DE_ITENS_VENDIDOS(
NUMERO VARCHAR (5),
CODIGO VARCHAR (5),
QUANTIDADE INT,
PRECO FLOAT
);

CREATE TABLE TABELA_DE_ITENS_VENDIDOS
(
NUMERO VARCHAR(5) NOT NULL,
CODIGO VARCHAR(10) NOT NULL,
QUANTIDADE FLOAT NULL,
PRECO FLOAT NULL,
PRIMARY KEY (NUMERO, CODIGO)
);

ALTER TABLE TABELA_DE_ITENS_VENDIDOS
ADD CONSTRAINT FK_TABELA_DE_VENDAS
FOREIGN KEY (NUMERO) REFERENCES TABELA_DE_VENDAS (NUMERO);

ALTER TABLE TABELA_DE_ITENS_VENDIDOS
ADD CONSTRAINT FK_PRODUTOS
FOREIGN KEY (CODIGO) REFERENCES PRODUTOS (CODIGO);
